### ISSUE TITLE
"Legacy" tag/branch

### ISSUE THREAD

**Issue by OscarL** [Teknomancer/beconverter#6]
Might be a good idea to create a "legacy" branch (or at least a tag) around 1d2e807ece4800d934217618b251bf5c1c3bed50.

That way we should be free to remove the "Installer" and "Previous Versions" folders from master, while still providing easy access to any "software archeologist" :-)

That old/binary files removal would substantially reduce the size of the source tarball for the master branch (the ones HaikuPorts's recipes download to create builds/packages).

**Comment by Teknomancer** [comment]
Could you please do this if you know how? I'm a complete noob when it comes to Git.
